/* tslint:disable */
/* eslint-disable */
/**
 * Tokyo Land Price RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface HealthCheckResponse
 */
export interface HealthCheckResponse {
  /**
   *
   * @type {string}
   * @memberof HealthCheckResponse
   */
  message?: string
}

/**
 * Check if a given object implements the HealthCheckResponse interface.
 */
export function instanceOfHealthCheckResponse(value: object): value is HealthCheckResponse {
  return true
}

export function HealthCheckResponseFromJSON(json: any): HealthCheckResponse {
  return HealthCheckResponseFromJSONTyped(json, false)
}

export function HealthCheckResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HealthCheckResponse {
  if (json == null) {
    return json
  }
  return {
    message: json['message'] == null ? undefined : json['message'],
  }
}

export function HealthCheckResponseToJSON(json: any): HealthCheckResponse {
  return HealthCheckResponseToJSONTyped(json, false)
}

export function HealthCheckResponseToJSONTyped(
  value?: HealthCheckResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
  }
}
