/* tslint:disable */
/* eslint-disable */
/**
 * Tokyo Land Price RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface HealthCheckDefaultResponse
 */
export interface HealthCheckDefaultResponse {
  /**
   *
   * @type {string}
   * @memberof HealthCheckDefaultResponse
   */
  message: string
}

/**
 * Check if a given object implements the HealthCheckDefaultResponse interface.
 */
export function instanceOfHealthCheckDefaultResponse(
  value: object,
): value is HealthCheckDefaultResponse {
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function HealthCheckDefaultResponseFromJSON(json: any): HealthCheckDefaultResponse {
  return HealthCheckDefaultResponseFromJSONTyped(json, false)
}

export function HealthCheckDefaultResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HealthCheckDefaultResponse {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function HealthCheckDefaultResponseToJSON(json: any): HealthCheckDefaultResponse {
  return HealthCheckDefaultResponseToJSONTyped(json, false)
}

export function HealthCheckDefaultResponseToJSONTyped(
  value?: HealthCheckDefaultResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
  }
}
