/* tslint:disable */
/* eslint-disable */
/**
 * Tokyo Land Price RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PostMessageRequest
 */
export interface PostMessageRequest {
  /**
   *
   * @type {string}
   * @memberof PostMessageRequest
   */
  message: string
  /**
   *
   * @type {number}
   * @memberof PostMessageRequest
   */
  lat?: number
  /**
   *
   * @type {number}
   * @memberof PostMessageRequest
   */
  lon?: number
  /**
   *
   * @type {boolean}
   * @memberof PostMessageRequest
   */
  isPoint?: boolean
  /**
   *
   * @type {string}
   * @memberof PostMessageRequest
   */
  language?: PostMessageRequestLanguageEnum
}

/**
 * @export
 */
export const PostMessageRequestLanguageEnum = {
  En: 'en',
  Ja: 'ja',
} as const
export type PostMessageRequestLanguageEnum =
  (typeof PostMessageRequestLanguageEnum)[keyof typeof PostMessageRequestLanguageEnum]

/**
 * Check if a given object implements the PostMessageRequest interface.
 */
export function instanceOfPostMessageRequest(value: object): value is PostMessageRequest {
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function PostMessageRequestFromJSON(json: any): PostMessageRequest {
  return PostMessageRequestFromJSONTyped(json, false)
}

export function PostMessageRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostMessageRequest {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
    lat: json['lat'] == null ? undefined : json['lat'],
    lon: json['lon'] == null ? undefined : json['lon'],
    isPoint: json['is_point'] == null ? undefined : json['is_point'],
    language: json['language'] == null ? undefined : json['language'],
  }
}

export function PostMessageRequestToJSON(json: any): PostMessageRequest {
  return PostMessageRequestToJSONTyped(json, false)
}

export function PostMessageRequestToJSONTyped(
  value?: PostMessageRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
    lat: value['lat'],
    lon: value['lon'],
    is_point: value['isPoint'],
    language: value['language'],
  }
}
