/* tslint:disable */
/* eslint-disable */
/**
 * Tokyo Land Price RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PostMessage200Response
 */
export interface PostMessage200Response {
  /**
   *
   * @type {string}
   * @memberof PostMessage200Response
   */
  response?: string
}

/**
 * Check if a given object implements the PostMessage200Response interface.
 */
export function instanceOfPostMessage200Response(value: object): value is PostMessage200Response {
  return true
}

export function PostMessage200ResponseFromJSON(json: any): PostMessage200Response {
  return PostMessage200ResponseFromJSONTyped(json, false)
}

export function PostMessage200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostMessage200Response {
  if (json == null) {
    return json
  }
  return {
    response: json['response'] == null ? undefined : json['response'],
  }
}

export function PostMessage200ResponseToJSON(json: any): PostMessage200Response {
  return PostMessage200ResponseToJSONTyped(json, false)
}

export function PostMessage200ResponseToJSONTyped(
  value?: PostMessage200Response | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    response: value['response'],
  }
}
