/* tslint:disable */
/* eslint-disable */
/**
 * Tokyo Land Price RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PostMessageRequest
 */
export interface PostMessageRequest {
  /**
   *
   * @type {string}
   * @memberof PostMessageRequest
   */
  message: string
}

/**
 * Check if a given object implements the PostMessageRequest interface.
 */
export function instanceOfPostMessageRequest(value: object): value is PostMessageRequest {
  if (!('message' in value) || value['message'] === undefined) return false
  return true
}

export function PostMessageRequestFromJSON(json: any): PostMessageRequest {
  return PostMessageRequestFromJSONTyped(json, false)
}

export function PostMessageRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostMessageRequest {
  if (json == null) {
    return json
  }
  return {
    message: json['message'],
  }
}

export function PostMessageRequestToJSON(json: any): PostMessageRequest {
  return PostMessageRequestToJSONTyped(json, false)
}

export function PostMessageRequestToJSONTyped(
  value?: PostMessageRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    message: value['message'],
  }
}
