/* tslint:disable */
/* eslint-disable */
/**
 * Tokyo Land Price RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PostMessageResponse
 */
export interface PostMessageResponse {
  /**
   *
   * @type {string}
   * @memberof PostMessageResponse
   */
  response?: string
}

/**
 * Check if a given object implements the PostMessageResponse interface.
 */
export function instanceOfPostMessageResponse(value: object): value is PostMessageResponse {
  return true
}

export function PostMessageResponseFromJSON(json: any): PostMessageResponse {
  return PostMessageResponseFromJSONTyped(json, false)
}

export function PostMessageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostMessageResponse {
  if (json == null) {
    return json
  }
  return {
    response: json['response'] == null ? undefined : json['response'],
  }
}

export function PostMessageResponseToJSON(json: any): PostMessageResponse {
  return PostMessageResponseToJSONTyped(json, false)
}

export function PostMessageResponseToJSONTyped(
  value?: PostMessageResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value
  }

  return {
    response: value['response'],
  }
}
