/* tslint:disable */
/* eslint-disable */
/**
 * Tokyo Land Price RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { ErrorResponse, HealthCheckResponse } from '../models/index'
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  HealthCheckResponseFromJSON,
  HealthCheckResponseToJSON,
} from '../models/index'

/**
 *
 */
export class HealthApi extends runtime.BaseAPI {
  /**
   * Health check endpoint
   */
  async healthCheckRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HealthCheckResponse>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    let urlPath = `/health`

    const response = await this.request(
      {
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      HealthCheckResponseFromJSON(jsonValue),
    )
  }

  /**
   * Health check endpoint
   */
  async healthCheck(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HealthCheckResponse> {
    const response = await this.healthCheckRaw(initOverrides)
    return await response.value()
  }
}
