/* tslint:disable */
/* eslint-disable */
/**
 * Tokyo Land Price RAG API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { ErrorResponse, PostMessageRequest, PostMessageResponse } from '../models/index'
import {
  ErrorResponseFromJSON,
  ErrorResponseToJSON,
  PostMessageRequestFromJSON,
  PostMessageRequestToJSON,
  PostMessageResponseFromJSON,
  PostMessageResponseToJSON,
} from '../models/index'

export interface PostMessageOperationRequest {
  postMessageRequest: PostMessageRequest
}

/**
 *
 */
export class MessagesApi extends runtime.BaseAPI {
  /**
   * Send a message and receive a response
   */
  async postMessageRaw(
    requestParameters: PostMessageOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PostMessageResponse>> {
    if (requestParameters['postMessageRequest'] == null) {
      throw new runtime.RequiredError(
        'postMessageRequest',
        'Required parameter "postMessageRequest" was null or undefined when calling postMessage().',
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    headerParameters['Content-Type'] = 'application/json'

    let urlPath = `/messages`

    const response = await this.request(
      {
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: PostMessageRequestToJSON(requestParameters['postMessageRequest']),
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PostMessageResponseFromJSON(jsonValue),
    )
  }

  /**
   * Send a message and receive a response
   */
  async postMessage(
    requestParameters: PostMessageOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PostMessageResponse> {
    const response = await this.postMessageRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
